#ifndef CIPHERSLIBRARY_GLOBAL_H
#define CIPHERSLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CIPHERSLIBRARY_LIBRARY)
#  define CIPHERSLIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define CIPHERSLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // CIPHERSLIBRARY_GLOBAL_H
